### PR TITLE
update dependencies

### PR DESCRIPTION
**Pull request by wsodsong**
## Description

Update dependencies of Aida to the latest Sonic develop

Sonic: `8dd1235621ad5d6e38530a9e9defa144176159fc`
Tosca: `aa99babe0a10a3facbaba4f67382379e568d44b3`
Carmen: `8b3c25fd1ff810f1c7274ff07d387ce59ed2258c`

### CODE REVIEW

**Comment by cabrador** [comment]
Could you also update carmen to [this](https://github.com/Fantom-foundation/Carmen/commit/e8dc12374917e3e86493fda931831dcd677618f9) version?

**Comment by wsodsong** [comment]
I am aligning the version to carmen in Sonic develop. Is there a plan to update carmen in Sonic?

**Comment by wsodsong** [comment]
Updated versions

**Review by matejmode — DISMISSED** [review]

**Review by cabrador — APPROVED** [review]

**Review by cabrador — CHANGES_REQUESTED** [review]
Sorry for changing the review. I thought every fix necessary to pass the `geth-tests` was already merged. I will ping you with the version once we have it.

**Comment by kjezek** [comment]
We should update to the latest commit: https://github.com/Fantom-foundation/Carmen/commit/8b3c25fd1ff810f1c7274ff07d387ce59ed2258c 

It contains all changed needed for ethereum-tests

**Review by cabrador — APPROVED** [review]

**Pull request merged**
